### ISSUE TITLE
Client.open and collections

### ISSUE THREAD

**Issue by srepmub** [stac-utils/pystac-client#103]
Client currently inherits from Catalog, so cannot be used with a Collection object ("..does not represent a Client instance").

We currently have hierarchy of collections, and would like to be able to search at different levels. It may be that this is a weird use case, but from glancing at the STAC specs, that should be fine (as collections are an extension of catalogs?)..?

For now we lookup the 'search' link manually, and use ItemSearch directly, and that seems to work fine..

**Comment by matthewhanson** [comment]
Hi @srepmub , note that the latest version on the main branch will be published shortly as 0.3.0-beta.1

I don't think it changes anything for this use case. There is a `CollectionClient.get_items` function which will use a Collections /items endpoint, but doesn't currently support searching with parameters. 

The recommended way to use the library is to use the `Client` class, as this allows you to open up an API and read the Conformance Classes so it can check before allowing certain functions or keywords.  Then you can just use `Client.search` with the collection ID you wish to search and it's the same thing as using the /items endpoint with one important difference.  The STAC API /search endpoint allows POST and GET.  The /collections/<collection_id>/items endpoint only supports GET as POST is used in the transaction extension.  This can be important in some cases where you have a large geometry that is too big for GET requests.

However, as you're doing, you can always use the ItemSearch class directly. 

A future version should add search parameters to the `CollectionClient.get_items` which I think would resolve your use case. Would this be sufficient, or is there something else you are looking for?

**Comment by srepmub** [comment]
thanks. I guess I'm mostly just wondering if our collection hierarchy is allowed by the STAC specs (I think it should be), and if so, API-wise, if it wouldn't be nicer to make Client also accept a Collection endpoint (since it's just an extension of a Catalog)..? if you agree, I would be happy to try and make a pull request.

**Comment by matthewhanson** [comment]
Sorry for the delay on this response @srepmub . 

There's a couple potential problems here. One is that a `Client` maps to a STAC Catalog, which is not a Collection (as of STAC 1.0.0 a Collection does not technically inherit from a Catalog). So what you would want is a way to open up a Collection with CollectionClient.  However that does not solve your problem since you have a `search` endpoint under your Collections.

While this sort of nested hierarchy you are using is allowable in the STAC spec, the placement of your search endpoints do not follow the STAC API spec. With the stac-api-spec the root is a Catalog and potentially has a `search` endpoint. However, Collection children within an API have an `items` endpoint, not a `search` endpoint.

So sounds like what you need is perhaps the ability to open up a Collection directly with CollectionClient, but also to have pystac-client support search parameters at the `items` endpoint, via the `get_items` function.

**Comment by gadomski** [comment]
I'll bump this issue as I just ran into it when trying to use **pystac-client** to implement API support for `stac info` and `stac describe` (https://github.com/stac-utils/stactools/issues/1). It's very reasonable to ask:

```shell
stac info my-collection.json
```

However, if you ask (using `Client.open` instead of `pystac.from_file`):

```
stac info https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a
```

You error our with the `... is not a "Client"` error. While `Collection` does not inherit from `Catalog`, they are (correctly, IMO) used interchangeably for discovery.

I'm not quite sure what the technical solution should be in **pystac-client**, but this won't be the last we hear of `Catalog` vs `Collection`.

**Comment by matthewhanson** [comment]
It seems reasonable that one should be able to open a Collection as a Catalog since a Collection in STAC is also a valid Catalog (other than the 'type' field). However since the spec does not actually specify inheritance there could be a future change that renders a Collection invalid as a Catalog.

One option could be to be able to open Collections as Catalogs, in which case you would lose any of the Collection-level fields, but could use it as a normal catalog.

Not sure what should be changed here, looking for opinions on what specific changes should be made.

**Comment by gadomski** [comment]
> However since the spec does not actually specify inheritance there could be a future change that renders a Collection invalid as a Catalog.

I often implement a `Container` interface that holds the methods common between `Collection` and `Catalog` -- maybe something we could add to PySTAC in the future.

> One option could be to be able to open Collections as Catalogs, in which case you would lose any of the Collection-level fields, but could use it as a normal catalog.

👍🏽, maybe with a warning explaining what's happening. IMO `pystac-client` shouldn't be the library you're using for `Collection`-specific operations.

**Comment by philvarner** [comment]
`info` is no longer a command, only `collections` and `search`

**Comment by gadomski** [comment]
`info` was for `stactools`, this issue is (I think) still valid -- basically, you should be able to open a `Client` for a `Collection`. It's probably just a matter of detecting `type == collection` and instating a `CollectionClient`? I can look into this.
