### ISSUE TITLE
Multiple filters with same operators NOT working

### ISSUE THREAD

**Issue by simonevaccari** [stac-utils/pystac-client#134]
Hello, 

I'm following the guidelines of the **CQL Filters section** of [this tutorial](https://github.com/stac-utils/pystac-client/blob/47812c6f59e8f81956e62f2149d4becc34e7aae0/docs/tutorials/cql-filter.ipynb) in order to filter a Sentinel-1 collection with multiple filters. 

The combination of filters work when using filters with different operators, eg:
```
filt = {
    "eq": [{"property": "sensor_type"}, "radar"],
    "lte": [{"property": "sat:relative_orbit"}, 60],
    "gte": [{"property": "sat:relative_orbit"}, 40]
}
```

However, when multiple filters with the same operator (e.g. "eq") are used, this syntax does not work: 
```
filt = {
    "eq": [{"property": "sensor_type"}, "radar"],
    "eq": [{"property": "sar:instrument_mode"}, "IW"],
    "eq": [{"property": "sar:polarizations"}, "VV"],
    "lte": [{"property": "sat:relative_orbit"}, 60],
    "gte": [{"property": "sat:relative_orbit"}, 40]
}
```
This is because **filt** is a dictionary, hence its "keys" need to be unique. Therefore in this case, only the last "eq" operator is saved (i.e. "sar:polarizations == VV") together with the "lte" and "gte" operators, while the other 2 "eq" are overwritten and discarded.

Following this syntax, I attempted to add multiple "eq" operators within an array, such as below, but it does not work. 
```
filt = {
    "eq": [
        [{"property": "sensor_type"}, 'radar'],
        [{"property": "sar:instrument_mode"}, 'IW'],
        [{"property": "sar:polarizations"}, 'VV']
    ],
    "gte": [{"property": "sat:relative_orbit"}, 120],
    "lte": [{"property": "sat:relative_orbit"}, 130],
}
```

I even tried to follow the syntax of **Example 3** of [this tutorial](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#example-3-and-cql2-json-post), but it fails with errors, and I am not sure it is the correct approach.  

How can filtering with multiple filters with the same operators be obtained? Could you please point me to the right direction?

Many thanks,
Simone

**Comment by mmcfarland** [comment]
Hi @simonevaccari, you can use an `and` operator to group additional operators that have the same key. In your case, it looks like all the operators are meant to be and'd together, so they could all be added to a single list. Here's an example that returns correct results for a sentinel-2 filter that has a similar structure to yours:

```
search = catalog.search(filter_lang="cql2-json", filter={
  "op": "and",
  "args": [
    {"op": "=", "args": [{"property": "sat:orbit_state"}, "descending"]},
    {"op": "=", "args": [{"property": "s2:datatake_type"}, "INS-NOBS"]},
    {"op": "=", "args": [{"property": "s2:mgrs_tile"}, "31TBG"]}
  ]
})
```

Note that the syntax used here is for CQL2-JSON, rather than the older CQL referenced in that tutorial. CQL2 is supported in pgStac 0.4.0 and up. If your backend only supports earlier versions, the `and` operator is still the right approach, but the specific syntax is a little changed. Also note that pystac-client v0.3.2 is requred to use the `filter_lang` argument in my example above.

[Here's a full example](https://gist.github.com/mmcfarland/bb8a648f70aa797f61d5211ff3f5dba0) against the Microsoft Planetary Computer which has a public API with support for CQL2:

**Comment by matthewhanson** [comment]
Hello @simonevaccari , I'm wondering if you are still having any problems with this. It looks like in might have been a usage issue based on @mmcfarland's response. I'm closing this for now but feel free to comment or open a new issue for anything.
