### ISSUE TITLE
Should API inherit from Catalog?

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac-client#19]
The `API` class currently [inherits from `pystac.Catalog`](https://github.com/stac-utils/pystac-api-client/blob/eadc4d48b3f09e7bae1671933d5bddc4dc205005/pystac_api/api.py#L21). This was originally done because the an API landing page has to be valid STAC Catalog according to the spec, and because it made all of the typical methods of a `pystac.Catalog` immediately available, which seemed convenient. 

However, `pystac.Catalog` has a bunch of methods used for writing that really don't apply to the `API` class. One option would be to overwrite these so that they are either no-ops or raise a `NotImplemented` error. Another option would be to use composition rather than inheritance and have the landing page be an attribute within a completely separate `API` class.

Opening this issue to start a discussion on what the best approach would be for this.

**Comment by matthewhanson** [comment]
Talked about this briefly in STAC mtg, then @duckontheweb and I discussed.

The consensus is that it's nice for a user to be able to use the same tool on both a Catalog and an API without having to worry.
Turns out that the API class inheriting from Catalog does exactly this. You can open up a static Catalog with API(), it's just the search functions that won't work.  Communicating exactly what is supported to the user is part of the Conformance classes which will be fleshed out more as more APIs implement that.

It's true that there are methods for writing that wouldn't apply to an API (unless transactions are supported), but we can throw an exception when trying to write to an API but still allow writing with other catalogs.

To this end we've renamed this library `pystac-client` to be more agnostic if the data is static or an API.
