### ISSUE TITLE
Expand partial datetimes when querying

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac-client#29]
STAC APIs should accept just dates and shouldn't require full datetimes (e.g., 2020-01-01 vs 2020-01-01T12:00:00Z), since querying by time component isn't a common use case.

However, it appears that not all existing STAC API implementations support this and may require full datetimes.

The client can handle this logic and be explicit about the datetimes it requests. 
Users should be able to specify:

- A single year which should translate to a datetime range encompassing the whole year
- A range of years which should translate to beginning of year1 to end of year2
- A single month or range of months (2020-01/2020-02) which should act as above
- A single fully complete datetime, which should be unaltered
- A single date which should translate to a range encompassing the whole day
- A date range translate to beginning of date1 to end of date2

Update documentation with examples showing all the possible inputs

**Comment by lossyrob** [comment]
Just hit on this - I like the idea of having pystac-client make valid datetimes on the client side, and also will make a fix server side to handle date formats. Right now there's a validation error that's given by the server, which isn't visible to the pystac-client user. Would it make sense to bubble up messages from servers, such as 400's, so that the user can see why the server rejected the search?

**Comment by lossyrob** [comment]
Ah, I see that my second point was already covered in #27.

**Comment by matthewhanson** [comment]
I think the proposed above follows the spec for what should be allowed, but worth reviewing as part of this:

https://github.com/radiantearth/stac-api-spec/blob/master/item-search/openapi.yaml#L120

https://tools.ietf.org/html/rfc3339#section-5.6
