### ISSUE TITLE
catalog.search method returns NotImplementedError 

### ISSUE THREAD

**Issue by jbaum53** [stac-utils/pystac-client#43]
Using the python library after instantiating a client connection to a STAC server, calling the catalog.search method returns a NotImplementedError. Maybe this has to do with how the subclass inherits method definitions from the parent class?

Example method that returns NotImplementedError on line 3:

`def my_read_method(stacserver_url):`

      catalog = Client.open(stacserver_url)
      mysearch = catalog.search(bbox=[-72.5,40.5,-72,41], max_items=10)
      return(f"{mysearch.matched()} items found")`

**Comment by duckontheweb** [comment]
These lines are probably the culprit: https://github.com/stac-utils/pystac-client/blob/main/pystac_client/client.py#L249-L256.

If the API publishes a `"conformsTo"` property then `Client` will check that it includes an [Item Search Conformance URI](https://github.com/radiantearth/stac-api-spec/blob/master/item-search/README.md#stac-api---item-search). If not, then it assumes the API doesn't implement the Item Search endpoint and raises a `NotImplementedError`.  Since the conformance URIs have changed a bit as the spec has evolved, we allow for a couple of possible URIs. You can check out the [`STAC_API_ITEM_SEARCH` conformance class](https://github.com/stac-utils/pystac-client/blob/main/pystac_client/conformance.py#L91-L95) to see which URIs it accepts.

That being said, there are a lot of APIs out there that don't publish all of the conformance URIs described in the current version of the spec, so it would probably be good to have a way to override this check and just try the `/search` endpoint if the user wants.

**Comment by matthewhanson** [comment]
@jbaum53 RIght now those checks are all ignored if there are no conformance links (because as @duckontheweb said things are in flux right now and most implementations do not have conformance links).  In the next version we'll have a way to forcibly ignore conformance links, even if they are present.

However your error implies that there are conformance links in the server, just not the right ones.  Did you add conformsTo to your deployment of stac-server?

**Comment by jbaum53** [comment]
Thanks all - @matthewhanson I had been checking against the NASA CMR endpoint (which is confirmed to not have a "rel":"search" pair on the base URL.) Checking against a different endpoint worked just fine.

Thanks again for the direction here!
