### ISSUE TITLE
Add documentation for retry configuration in pystac-client and enable them by default

### ISSUE THREAD

**Issue by pv-98** [stac-utils/pystac-client#520]
Please refer the [API error](https://github.com/microsoft/planetary-computer-apis/issues/176) issue for the problems faced.

**Comment by gadomski** [comment]
Don't see why that wouldn't work, but since we're a network-y library, I think it'd make sense to add retries as a configuration option to `StacApiIO`. I'm marking this issue as an enhancement to track.

FYI here's the relevant bits of the `RetryStacIO` in **pystac**: https://github.com/stac-utils/pystac/blob/e196e50bd23b52169d2f85fcd2d126fc7258684f/pystac/stac_io.py#L439-L444
