### ISSUE TITLE
Number of matched items with limit 0 invalid

### ISSUE THREAD

**Issue by jonas-eberle** [stac-utils/pystac-client#73]
Hi all, 

according to the STAC API specification, the `limit `parameter needs to be between 1 and 10.000: 
https://github.com/radiantearth/stac-api-spec/blob/dev/item-search/openapi.yaml#L200-L204

Within the `matched` function, the limit is set to 0 to just get the number of found features within a query request. This request results in an exception (e.g., when using the stac-fastapi (pgstac) API backend) because the API returns an HTTP status code not equal to 200, which is fine according to the STAC API specification. 

https://github.com/stac-utils/pystac-client/blob/8282ef37b8ce97c15a3af9ba3292b51c3935def7/pystac_client/item_search.py#L373-L375

Maybe the limit parameter needs to be change from 0 to 1?

Best
Jonas

**Comment by matthewhanson** [comment]
I actually wasn't aware that there was a lower limit of 1 on requests.  I've been using limit=0 for years, since the beginning of STAC to get just a total count of matched items and have always implemented it in clients and servers.  I personally would be in favor of the spec changing to allow limit=0, but in the meantime I suppose it should just be changed to 1.

cc @philvarner
